### ISSUE TITLE
Update Mobile Wallet instructions

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystemArchive/docs-legacy#174]
- Update install information about iOS and fix the links
- Update screenshot and add new functionalities  to the instructions

**Comment by tpscrpt** [comment]
Sure, will hop on during my free time @kristjank ; may I be assigned?

**Comment by kristjank** [comment]
sure

**Comment by kristjank** [comment]
@JeremiGendron  go ahead

**Comment by tpscrpt** [comment]
#196 done, please review when the time comes. I'll be happy to make more changes.
