### ISSUE TITLE
The development docs are wildly outdated!

### ISSUE THREAD

**Issue by tpscrpt** [ArkEcosystemArchive/docs-legacy#232]
**Is your feature request related to a problem? Please describe.**
I personally was left behind for a period of time when the default branch switched to master and there was a new file called UPGRADE.md introduced to the develop branch.

It would have been super cool to have an updated version of the docs which reflect installation instructions for less-well-versed individuals wishing to run a few tests and explore the Core.

**Describe the solution you'd like**
A nicely written, updated version of the development docs for Core

**Describe alternatives you've considered**
Linking to the UPGRADE.md file :worried: 

**Additional context**
Submitting a PR with what I think the new changes should be, feel free to comment on it!

**Comment by KaiserKarel** [comment]
I am currently working on refurbishing the docs, both style, context and content. Can you specify what is missing and where we need to direct some attention?

**Comment by tpscrpt** [comment]
I've made a PR with those changes

**Comment by faustbrian** [comment]
Should be resolved with the updates of the last few weeks.

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
