### ISSUE TITLE
Typo error in documentation

### ISSUE THREAD

**Issue by slyg** [ArkEcosystemArchive/docs-legacy#273]
**Describe the bug**

This is simply a small typo I noticed while browsing the doc: graphQL misspelled as _grahpQL_.

**Comment by ghost** [comment]
@slyg Thanks for opening this issue, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@adrian69 @faustbrian @supaiku0 - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
@slyg This issue has been closed. If you wish to re-open it please provide additional information.
