### ISSUE TITLE
yarn start in core/ is not supported anymore

### ISSUE THREAD

**Issue by Hugoo** [ArkEcosystemArchive/docs-legacy#326]
Following commit https://github.com/ArkEcosystem/core/commit/3dc9a6385ff998284915c31292ca9a70bf991d37, the command `yarn start` in the `core/` package doesn't exist anymore. The [documentation](https://github.com/ArkEcosystem/docs/blob/404351543f4cc1a7142579e8223fbf96410bdd19/docs/guidebook/core/development.md) should be updated as it still refers to the `yarn start` command.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
