### ISSUE TITLE
Dead link to the database section on the core/development page.

### ISSUE THREAD

**Issue by Hugoo** [ArkEcosystemArchive/docs-legacy#328]
**Describe the bug**
On the [Development](https://docs.ark.io/guidebook/core/development.html#database) page, in the database section, there is a dead link to the [database section](https://docs.ark.io/guidebook/core/database.html#introduction)

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/docs/pull/331

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
