### ISSUE TITLE
Running yarn test in core/ is outdated

### ISSUE THREAD

**Issue by Hugoo** [ArkEcosystemArchive/docs-legacy#329]
**Describe the bug**
The [doc](https://docs.ark.io/guidebook/core/development.html#getting-started) states that one can run `yarn test` in individual packages but this command doesn't exist anymore in the `core/` package (after this commit : https://github.com/ArkEcosystem/core/commit/3dc9a6385ff998284915c31292ca9a70bf991d37)

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/docs/pull/331

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
