### ISSUE TITLE
Outdated code snippets

### ISSUE THREAD

**Issue by dated** [ArkEcosystemArchive/docs-legacy#343]
**Describe the problem**

The code snippets are mostly outdated (javascript, still using `ARK_XXX` env vars, ...) and should be replaced. Should the replacing code snippets be taken from the core `master` or `develop` branch @faustbrian?

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by faustbrian** [comment]
Should be based on develop to keep things updated and the environment variables shouldn't change between master and develop anymore as the CORE prefix is now fixed.

**Comment by dated** [comment]
Thanks. I'll get it done over the weekend.

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
