### ISSUE TITLE
How to get started with Core development

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystemArchive/docs-legacy#360]
https://github.com/ArkEcosystem/docs/commit/784ccbea77e616f37347d93f9f96758486dceaae

**Comment by MisterAwesome23** [comment]
Is this thread a starting point for getting started with documentation contributions to Ark? I am want to start contributing with documentation projects with reference to Google Season of Docs? Is this the right place or can someone please guide me where to. 
Thank you :)

**Comment by samharperpittam** [comment]
Hello @MisterAwesome23 

Thank you for your interest in ARK and the GSoD program.
We will be selecting a technical writer following an official application via Google. You can find how to do that here - https://developers.google.com/season-of-docs/docs/tech-writer-guide

You can view our list of project ideas for the GSoD program here - https://docs.ark.io/guidebook/contribution-guidelines/gsod.html

You can also view our documentation guidebook here - https://docs.ark.io/guidebook/

If you see a project within the project list that you have an interest in working on, we'd love for you to send an official application. If you have any further questions, feel free to reach out to me at gsod@ark.io

Regards,

Sam

**Comment by faustbrian** [comment]
Delaying this until 3.0 is released.
