### ISSUE TITLE
Reference to a missing docker/testnet folder on Setup Your Dev Environment page

### ISSUE THREAD

**Issue by Hugoo** [ArkEcosystemArchive/docs-legacy#368]
**Describe the bug**
The [How to Setup Your Dev Environment](https://github.com/ArkEcosystem/docs/blob/b7688577d055acc2389816dbf7564c9b2fcaeb91/docs/guidebook/developer/setup-dev-environment.md) page makes a reference to a `docker/testnet` folder which does not exist. There is only a [production](https://github.com/ArkEcosystem/core/tree/master/docker) folder in it.

**Expected behavior**
The [How to Setup Your Dev Environment](https://github.com/ArkEcosystem/docs/blob/b7688577d055acc2389816dbf7564c9b2fcaeb91/docs/guidebook/developer/setup-dev-environment.md) page should be accurate and up to date with the [core](https://github.com/ArkEcosystem/core) repository.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by dileepajayakody** [comment]
I've added a pull request to add back the `testnet` db docker scripts to `master` branch.
see : [pull request](https://github.com/ArkEcosystem/core/pull/2709)

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
