### ISSUE TITLE
Term usage all over the place and more

### ISSUE THREAD

**Issue by tpscrpt** [ArkEcosystemArchive/docs-legacy#38]
[more to fix] The problem stems from the fact that there is no clear indication of how to use terms when documenting Ark.

There are many occurrences of terms like "blockchain" either being capitalized or not across various documents.

Also, I've noticed that URLs are sometimes not attached to any link, which would imply the reader is supposed to manually copy and paste it into the address bar (tedious on mobile).

I've spotted use of icons which should be credited as they are externally owned, my recommendation is to require a references component on every document for standardized credit, references and mentions.

I have made my best effort today in establishing guidelines for writing documentation, and would like to contribute much more to offering a good experience to new Ark Community members.

**Comment by tpscrpt** [comment]
reading through this, will submit substantial PR

**Comment by kristjank** [comment]
@JeremiGendron is this still active and relevant

**Comment by tpscrpt** [comment]
yes, making changes to many files intermittently @kristjank will close this week

**Comment by tpscrpt** [comment]
#86
