### ISSUE TITLE
Repository management - GitHub issue colors not working

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystemArchive/docs-legacy#4]
On [this page](https://docs.ark.io/developers/guidelines/repository-management.html#how-to-organize-github-issues-pull-requests) in the docs, the color images aren't loaded. Console shows this error: `Refused to load https://placehold.it/15/fef2c0/000000?text=+ because it does not appear in the img-src directive of the Content Security Policy.`

**Comment by faustbrian** [comment]
Solved.
