### ISSUE TITLE
delegates/getNextForgers endpoint not documented

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystemArchive/docs-legacy#41]
The [delegates/getNextForgers](https://node1.arknet.cloud/api/delegates/getNextForgers) endpoint is not documented in the API 1.0 docs. Is there a specific reason that this wasn't done? @mvega3 @faustbrian

**Comment by faustbrian** [comment]
Must have been an oversight but afaik the endpoint will be removed in the future anyways.
