### ISSUE TITLE
ALL the links in the /docs folder's README.md file are making references to non-existent pages.

### ISSUE THREAD

**Issue by race2infinity** [ArkEcosystemArchive/docs-legacy#417]
**Expected Behavior**

ALL the links in the [ArkEcosystem/docs/docs/README.md](https://github.com/ArkEcosystem/docs/blob/master/docs/README.md) file must make references to proper and existent pages.

For eg -
In the [README.md](https://github.com/ArkEcosystem/docs/blob/master/docs/README.md), if I click on "From Blockchain to ARK", it should redirect me should take me to [this](https://github.com/ArkEcosystem/docs/tree/master/docs/introduction) page.

**Current Behavior**

Currently, ALL the links in the [README.md](https://github.com/ArkEcosystem/docs/blob/master/docs/README.md) file are redirecting me to a non-existent page.

For eg -
In the [README.md](https://github.com/ArkEcosystem/docs/blob/master/docs/README.md), if I click on "From Blockchain to ARK", it takes me to [this](
https://github.com/ArkEcosystem/docs/blob/master/introduction) page, a page that does not exist.

**Possible Solution**

ALL links in [README.md](https://github.com/ArkEcosystem/docs/blob/master/docs/README.md) have wrong file paths. ALL the links are missing  a  ```/docs``` parent directory reference at the beginning. Adding a ```/docs``` at the beginning of all the links fixes this problem.

For eg -
Making "From Blockchain to ARK" of the [README.md](https://github.com/ArkEcosystem/docs/blob/master/docs/README.md) file refer to ```/docs/introduction``` instead of ```/introduction``` [fixes](https://github.com/ArkEcosystem/docs/tree/master/docs/introduction) the problem. This needs to be done for ALL the links.

The "Desktop Wallet", "Mobile Wallet" and "Explorer" under [The ARK Ecosystem Tutorials](https://github.com/ArkEcosystem/docs/blob/master/docs/README.md#the-ark-ecosystem-tutorials) in the [README.md](https://github.com/ArkEcosystem/docs/blob/master/docs/README.md) file are making a reference to the file names with incorrect file extensions (```.html``` instead of ```.md```). 

Changing the extensions from ```.html``` to ```.md``` [fixes](https://github.com/ArkEcosystem/docs/blob/master/docs/tutorials/usage-guides/how-to-use-ark-desktop-wallet.md) this problem.

**Steps to Reproduce (for bugs)**

1. Go to the [README.md](https://github.com/ArkEcosystem/docs/blob/master/docs/README.md) file.
2. Click on "From Blockchain to ARK".
3. See error.

**Context**

I was browsing through the docs of ArkEcosystem, but due to incorrect links being referenced in the [README.md](https://github.com/ArkEcosystem/docs/blob/master/docs/README.md) file, I could not browse through the ArkEcosystem docs.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
