### ISSUE TITLE
Broken hyper-link reference in setup-dev-environment.html

### ISSUE THREAD

**Issue by dileepajayakody** [ArkEcosystemArchive/docs-legacy#420]
**Expected Behavior**
In the installation section **Lerna** hyper-link should be redirected to the Lerna project.

**Current Behavior**

Currently the **Lerna** hyper-link redirects to (https://lernajs.io/) which is not available.
 
**Possible Solution**
Link **Lerna** to it's github project page (https://github.com/lerna/lerna) 

**Steps to Reproduce (for bugs)**

1. Go to 'Installation' section.
2. Click on 'Lerna'.

**Context**
Currently I'm setting up Ark developer environment and also trying to contribute to the Arks docs project.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
