### ISSUE TITLE
The folder /docs/iot has a typo in the 4th sentence.

### ISSUE THREAD

**Issue by race2infinity** [ArkEcosystemArchive/docs-legacy#425]
**Expected Behavior**

Much like in crypto, ARK's approach to a "framework for mass adoption" ~fit's~ fits perfectly here.

**Steps to Reproduce (for bugs)**

1. Go to the [iot](https://github.com/ArkEcosystem/docs/tree/master/docs/iot) folder.
2. In the README.md, scroll down to _Much like in crypto, ARK's approach to a "framework for mass adoption" fit's perfectly here._
3. See typo.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
