### ISSUE TITLE
Typos in /docs/README.md

### ISSUE THREAD

**Issue by race2infinity** [ArkEcosystemArchive/docs-legacy#427]
**Expected Behavior**

1. Comma after "In this section" under [The Ark Ecosystem Guidebook](https://github.com/ArkEcosystem/docs/blob/master/docs/README.md#the-ark-ecosystem-guidebook).
2. The counterpart to the Guidebook, the tutorials ~contains~ contain practical code snippets  - [The Ark Ecosystem Tutorials](https://github.com/ArkEcosystem/docs/blob/master/docs/README.md#the-ark-ecosystem-tutorials)

**Steps to Reproduce (for bugs)**

1. Go to the [docs](https://github.com/ArkEcosystem/docs/tree/master/docs) folder.
2. Click on "README.md".
3. See typos.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
