### ISSUE TITLE
Inconsistencies in curl command examples on Public API docs

### ISSUE THREAD

**Issue by Lemii** [ArkEcosystemArchive/docs-legacy#430]
**Current Behavior**  
There are inconsistencies in the curl command examples on the Public API docs. 

There are command examples present in the following chapters:
* Blockchain
* Blocks
* Delegates

However, command examples are missing from these chapters:
* Node
* Peers 
* Transactions 
* Votes 
* Wallets 

**Possible Solution**  
Add curl command examples to the pages where they are missing, making the Public API documention more complete and easy to go through step by step.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.

**Comment by dated** [comment]
Some examples now use `-H` while others use `--header`. They should have the same form imho.

**Comment by Lemii** [comment]
All examples in the v2 documentation now use `--header`, as was already present on the pages: Blockchain, Blocks and Delegates.

It appears only the v1 documentation still use `-H`. I did not catch this, but I don't think this is worth fixing, considering v1 is legacy and the issue is already closed.
