### ISSUE TITLE
Outdated, invalid and/or inconsistent API response examples on Public API docs

### ISSUE THREAD

**Issue by Lemii** [ArkEcosystemArchive/docs-legacy#431]
**Current Behavior**  
The response examples shown on the Public API docs are often outdated, invalid and/or inconsistent. Examples of these issues are:   
* Missing data 
* Obsoleted data
* Devnet data shown for Mainnet API requests
* Mixed indentation size
* `...` character not used in a consistent manner

**Possible Solution**  
* Go through each API request used in the Public API documentation, and update the responses with up-to-date and correct data. 
* Use mainnet data only. This will make more sense for the end user, since the curl command examples all lead to the mainnet API. Using mainnet data only, the user can try the example commands and see the same results (where applicable) as shown on the docs.
* Use the same indentation for all reponse examples
* Use the `...` character in a consistent manner throughout the Public API docs (eg: use after first entry of a large array)

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
