### ISSUE TITLE
Add documentation of orderBy query parameter to all of the Public API docs

### ISSUE THREAD

**Issue by Lemii** [ArkEcosystemArchive/docs-legacy#436]
**Current Behaviour**  
There currently is no documentation for the `orderBy` query parameter for the following endpoints:

- Blocks
- Delegates
- Transactions
- Votes
- Wallets

Only the Peers page has *some* documentation, but it is too ambiguous.

Considering the importance of sorting and filtering, it is important to include instructions for the `orderBy` parameter in the pages listed above.

**Possible Solution**  
> All steps below must be executed for each of the individual endpoints.  

- Look up / find out about all sortable columns
- Test each individual column in a query
- Add `orderBy`to the query parameter table
- Add information about all sortable columns for the specific endpoint below the table
- Add an example curl command containing a `orderBy` parameter
- Add the example response

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
