### ISSUE TITLE
[cookbook] How to use core-tester-cli to send transactions

### ISSUE THREAD

**Issue by mariowhowrites** [ArkEcosystemArchive/docs-legacy#64]
Cookbook recipe on using core-tester-cli to send transactions

**Comment by kristjank** [comment]
reuse content from blogpost on dynamic fees

**Comment by tpscrpt** [comment]
WIPing on it

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/docs/commit/bb728a440dbf0987d1c5b6adc2225c89918e35c1
